M48
; DRILL file {KiCad 5.99.0-unknown-bf8a020501~134~ubuntu20.04.1} date Sat 02 Apr 2022 04:14:06 PM PDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-02T16:14:06-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,5.99.0-unknown-bf8a020501~134~ubuntu20.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C1.000
%
G90
G05
T1
X67.5Y-59.5
X71.5Y-59.5
X83.5Y-59.5
X87.5Y-59.5
T0
M30
