M48
; DRILL file {KiCad 5.99.0-unknown-d430fae05d~122~ubuntu20.04.1} date Thu Apr  1 22:15:06 2021
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2021-04-01T22:15:06-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,5.99.0-unknown-d430fae05d~122~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,ComponentDrill,NonPlated,NPTH
T1C2.500
%
G90
G05
T1
; not plated pad hole
X51.208Y-59.18
X51.208Y-82.42
X89.4Y-59.18
X89.4Y-82.42
T0
M30
